# Generated by Django 4.0.4 on 2022-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
